# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TGWSCAPP' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod "SDWebImage"
  pod "MBProgressHUD"
  pod "MJRefresh"
  pod "WechatOpenSDK"
  pod "UMCCommon"
  pod "UMCSecurityPlugins"
  pod "UMCAnalytics“
  pod "JPush"
  
  
  # Pods for TGWSCAPP

  target 'TGWSCAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TGWSCAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
